// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telebill.Data;

#nullable disable

namespace Telebill.Migrations
{
    [DbContext(typeof(TeleBillContext))]
    partial class TeleBillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Telebill.Models.Appeal", b =>
                {
                    b.Property<int>("AppealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppealID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppealId"));

                    b.Property<string>("AttachmentUri")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("AttachmentURI");

                    b.Property<int?>("DenialId")
                        .HasColumnType("int")
                        .HasColumnName("DenialID");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("OutcomeDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SubmittedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AppealId")
                        .HasName("PK__Appeal__BB684E107BD435EE");

                    b.HasIndex("DenialId");

                    b.ToTable("Appeal", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Arworkitem", b =>
                {
                    b.Property<int>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<DateOnly?>("NextActionDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("WorkId")
                        .HasName("PK__ARWorkit__2DE6D215F3736CC5");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("ClaimId");

                    b.ToTable("ARWorkitem", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.AttachmentRef", b =>
                {
                    b.Property<int>("AttachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttachID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachId"));

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileUri")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("FileURI");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AttachId")
                        .HasName("PK__Attachme__F517FC15AF512FE3");

                    b.HasIndex("ClaimId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("AttachmentRef", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Attestation", b =>
                {
                    b.Property<int>("AttestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttestId"));

                    b.Property<DateTime?>("AttestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AttestText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("EncounterID");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AttestId")
                        .HasName("PK__Attestat__23D3AEC482C75DC7");

                    b.HasIndex("EncounterId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Attestation", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditLog__A17F23B896C55F9D");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.BillingReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetricsJSON");

                    b.Property<string>("Scope")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ReportId")
                        .HasName("PK__BillingR__D5BD48E515F988CD");

                    b.ToTable("BillingReport", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.ChargeLine", b =>
                {
                    b.Property<int>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChargeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChargeId"));

                    b.Property<decimal?>("ChargeAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CptHcpcs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CPT_HCPCS");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("EncounterID");

                    b.Property<string>("Modifiers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevenueCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<int?>("Units")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ChargeId")
                        .HasName("PK__ChargeLi__17FC363B48345F36");

                    b.HasIndex("EncounterId");

                    b.ToTable("ChargeLine", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("ClaimStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("EncounterID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<string>("SubscriberRel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalCharge")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ClaimId")
                        .HasName("PK__Claim__EF2E13BB55C3AABF");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PlanId");

                    b.ToTable("Claim", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.ClaimLine", b =>
                {
                    b.Property<int>("ClaimLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClaimLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimLineId"));

                    b.Property<decimal?>("ChargeAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<string>("CptHcpcs")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CPT_HCPCS");

                    b.Property<string>("DxPointers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineNo")
                        .HasColumnType("int");

                    b.Property<string>("LineStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Modifiers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pos")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("POS");

                    b.Property<int?>("Units")
                        .HasColumnType("int");

                    b.HasKey("ClaimLineId")
                        .HasName("PK__ClaimLin__54106B81B1830998");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimLine", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.CodingLock", b =>
                {
                    b.Property<int>("CodingLockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodingLockID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodingLockId"));

                    b.Property<int?>("CoderId")
                        .HasColumnType("int")
                        .HasColumnName("CoderID");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("EncounterID");

                    b.Property<DateTime?>("LockedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Locked");

                    b.HasKey("CodingLockId")
                        .HasName("PK__CodingLo__A4770B1493213E96");

                    b.HasIndex("CoderId");

                    b.HasIndex("EncounterId");

                    b.ToTable("CodingLock", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Coverage", b =>
                {
                    b.Property<int>("CoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CoverageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverageId"));

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("GroupNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MemberID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("CoverageId")
                        .HasName("PK__Coverage__45403D9BDA4E59D8");

                    b.HasIndex("PatientId");

                    b.HasIndex("PlanId");

                    b.ToTable("Coverage", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Denial", b =>
                {
                    b.Property<int>("DenialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DenialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DenialId"));

                    b.Property<decimal?>("AmountDenied")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<int?>("ClaimLineId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimLineID");

                    b.Property<DateOnly?>("DenialDate")
                        .HasColumnType("date");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RemarkCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DenialId")
                        .HasName("PK__Denial__82E6F05CDEFC9B9C");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ClaimLineId");

                    b.ToTable("Denial", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Diagnosis", b =>
                {
                    b.Property<int>("DxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DxID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DxId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("EncounterID");

                    b.Property<string>("Icd10code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ICD10Code");

                    b.Property<int?>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("DxId")
                        .HasName("PK__Diagnosi__35BD562841D9DEA9");

                    b.HasIndex("EncounterId");

                    b.ToTable("Diagnosis", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.EligibilityRef", b =>
                {
                    b.Property<int>("EligibilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EligibilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EligibilityId"));

                    b.Property<DateTime?>("CheckedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CoverageId")
                        .HasColumnType("int")
                        .HasColumnName("CoverageID");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPayloadUri")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("RequestPayloadURI");

                    b.Property<string>("ResponsePayloadUri")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("ResponsePayloadURI");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EligibilityId")
                        .HasName("PK__Eligibil__962AC9DB2BD2E0E8");

                    b.HasIndex("CoverageId");

                    b.ToTable("EligibilityRef", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Encounter", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EncounterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncounterId"));

                    b.Property<string>("DocumentationUri")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("DocumentationURI");

                    b.Property<DateTime>("EncounterDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Pos")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("02")
                        .HasColumnName("POS");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Open");

                    b.Property<string>("VisitType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EncounterId")
                        .HasName("PK__Encounte__4278DD165DCAE1F0");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Encounter", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.FeeSchedule", b =>
                {
                    b.Property<int>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeId"));

                    b.Property<decimal?>("AllowedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CptHcpcs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CPT_HCPCS");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("ModifierCombo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("FeeId")
                        .HasName("PK__FeeSched__B387B209AAE4E531");

                    b.HasIndex("PlanId");

                    b.ToTable("FeeSchedule", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unread");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32EC8CF003");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AddressJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AddressJSON");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MRN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("PatientId")
                        .HasName("PK__Patient__970EC3462DC0E31F");

                    b.HasIndex(new[] { "Mrn" }, "UQ__Patient__C790FDB489FE611A")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.PatientBalance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BalanceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BalanceId"));

                    b.Property<string>("AgingBucket")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<DateOnly?>("LastStatementDate")
                        .HasColumnType("date");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BalanceId")
                        .HasName("PK__PatientB__A760D59E91F73F7B");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientBalance", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Payer", b =>
                {
                    b.Property<int>("PayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PayerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayerId"));

                    b.Property<string>("ClearinghouseCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PayerCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("PayerId")
                        .HasName("PK__Payer__0ADBE847890AAAF4");

                    b.ToTable("Payer", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.PayerPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("NetworkType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PayerId")
                        .HasColumnType("int")
                        .HasColumnName("PayerID");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Posdefault")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("02")
                        .HasColumnName("POSDefault");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TelehealthModifiersJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TelehealthModifiersJSON");

                    b.HasKey("PlanId")
                        .HasName("PK__PayerPla__755C22D73A52AAAE");

                    b.HasIndex("PayerId");

                    b.ToTable("PayerPlan", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.PaymentPost", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<string>("AdjustmentJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AdjustmentJSON");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<int?>("ClaimLineId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimLineID");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PostedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentId")
                        .HasName("PK__PaymentP__9B556A5879177ED2");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ClaimLineId");

                    b.HasIndex("PostedBy");

                    b.ToTable("PaymentPost", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.PriorAuth", b =>
                {
                    b.Property<int>("Paid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Paid"));

                    b.Property<DateOnly?>("ApprovedFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ApprovedTo")
                        .HasColumnType("date");

                    b.Property<string>("AuthNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<DateOnly?>("RequestedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Paid")
                        .HasName("PK__PriorAut__5986FD6D44EA84EE");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PlanId");

                    b.ToTable("PriorAuth", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProviderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Npi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("NPI");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Taxonomy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TelehealthEnrolled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ProviderId")
                        .HasName("PK__Provider__B54C689DBA7F593C");

                    b.HasIndex(new[] { "Npi" }, "UQ__Provider__C7DE9A1288CE189A")
                        .IsUnique();

                    b.ToTable("Provider", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.RemitRef", b =>
                {
                    b.Property<int>("RemitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RemitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemitId"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("BatchID");

                    b.Property<int?>("PayerId")
                        .HasColumnType("int")
                        .HasColumnName("PayerID");

                    b.Property<string>("PayloadUri")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("PayloadURI");

                    b.Property<DateTime?>("ReceivedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RemitId")
                        .HasName("PK__RemitRef__A1F3A787298AB3D2");

                    b.HasIndex("BatchId");

                    b.HasIndex("PayerId");

                    b.ToTable("RemitRef", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.ScrubIssue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IssueID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueId"));

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<int?>("ClaimLineId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimLineID");

                    b.Property<DateTime?>("DetectedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RuleId")
                        .HasColumnType("int")
                        .HasColumnName("RuleID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("IssueId")
                        .HasName("PK__ScrubIss__6C86162459062E5F");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ClaimLineId");

                    b.HasIndex("RuleId");

                    b.ToTable("ScrubIssue", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.ScrubRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<string>("ExpressionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExpressionJSON");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("RuleId")
                        .HasName("PK__ScrubRul__110458C2261FCA16");

                    b.ToTable("ScrubRule", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Statement", b =>
                {
                    b.Property<int>("StatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatementId"));

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SummaryJSON");

                    b.HasKey("StatementId")
                        .HasName("PK__Statemen__2B7E04222CBFCE1A");

                    b.HasIndex("PatientId");

                    b.ToTable("Statement", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.SubmissionBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BatchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<DateTime?>("BatchDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalCharge")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("BatchId")
                        .HasName("PK__Submissi__5D55CE384DE7D73B");

                    b.ToTable("SubmissionBatch", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.SubmissionRef", b =>
                {
                    b.Property<int>("SubmitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubmitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmitId"));

                    b.Property<DateTime?>("AckDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AckStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AckType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("BatchID");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<string>("ClearinghouseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ClearinghouseID");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CorrelationID");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmitDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SubmitId")
                        .HasName("PK__Submissi__421A8E1ED53F8917");

                    b.HasIndex("BatchId");

                    b.HasIndex("ClaimId");

                    b.ToTable("SubmissionRef", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCAC4D9BD9F6");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105340ED77520")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.X12837pRef", b =>
                {
                    b.Property<int>("X12id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("X12ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("X12id"));

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<DateTime?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PayloadUri")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("PayloadURI");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("X12id")
                        .HasName("PK__X12_837P__68BEC4B72FC858AE");

                    b.HasIndex("ClaimId");

                    b.ToTable("X12_837P_Ref", (string)null);
                });

            modelBuilder.Entity("Telebill.Models.Appeal", b =>
                {
                    b.HasOne("Telebill.Models.Denial", "Denial")
                        .WithMany("Appeals")
                        .HasForeignKey("DenialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Appeal__DenialID__58D1301D");

                    b.Navigation("Denial");
                });

            modelBuilder.Entity("Telebill.Models.Arworkitem", b =>
                {
                    b.HasOne("Telebill.Models.User", "AssignedToNavigation")
                        .WithMany("Arworkitems")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ARWorkite__Assig__5D95E53A");

                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("Arworkitems")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ARWorkite__Claim__5CA1C101");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Telebill.Models.AttachmentRef", b =>
                {
                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("AttachmentRefs")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Attachmen__Claim__3587F3E0");

                    b.HasOne("Telebill.Models.User", "UploadedByNavigation")
                        .WithMany("AttachmentRefs")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Attachmen__Uploa__367C1819");

                    b.Navigation("Claim");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("Telebill.Models.Attestation", b =>
                {
                    b.HasOne("Telebill.Models.Encounter", "Encounter")
                        .WithMany("Attestations")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Attestati__Encou__0B91BA14");

                    b.HasOne("Telebill.Models.Provider", "Provider")
                        .WithMany("Attestations")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Attestati__Provi__0C85DE4D");

                    b.Navigation("Encounter");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Telebill.Models.AuditLog", b =>
                {
                    b.HasOne("Telebill.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__AuditLog__UserID__60A75C0F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Telebill.Models.ChargeLine", b =>
                {
                    b.HasOne("Telebill.Models.Encounter", "Encounter")
                        .WithMany("ChargeLines")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ChargeLin__Encou__06CD04F7");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("Telebill.Models.Claim", b =>
                {
                    b.HasOne("Telebill.Models.Encounter", "Encounter")
                        .WithMany("Claims")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK__Claim__Encounter__1AD3FDA4");

                    b.HasOne("Telebill.Models.Patient", "Patient")
                        .WithMany("Claims")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Claim__PatientID__1BC821DD");

                    b.HasOne("Telebill.Models.PayerPlan", "Plan")
                        .WithMany("Claims")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Claim__PlanID__1CBC4616");

                    b.Navigation("Encounter");

                    b.Navigation("Patient");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Telebill.Models.ClaimLine", b =>
                {
                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("ClaimLines")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ClaimLine__Claim__2180FB33");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Telebill.Models.CodingLock", b =>
                {
                    b.HasOne("Telebill.Models.User", "Coder")
                        .WithMany("CodingLocks")
                        .HasForeignKey("CoderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__CodingLoc__Coder__160F4887");

                    b.HasOne("Telebill.Models.Encounter", "Encounter")
                        .WithMany("CodingLocks")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__CodingLoc__Encou__151B244E");

                    b.Navigation("Coder");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("Telebill.Models.Coverage", b =>
                {
                    b.HasOne("Telebill.Models.Patient", "Patient")
                        .WithMany("Coverages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Coverage__Patien__787EE5A0");

                    b.HasOne("Telebill.Models.PayerPlan", "Plan")
                        .WithMany("Coverages")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Coverage__PlanID__797309D9");

                    b.Navigation("Patient");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Telebill.Models.Denial", b =>
                {
                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("Denials")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Denial__ClaimID__55009F39");

                    b.HasOne("Telebill.Models.ClaimLine", "ClaimLine")
                        .WithMany("Denials")
                        .HasForeignKey("ClaimLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK__Denial__ClaimLin__55F4C372");

                    b.Navigation("Claim");

                    b.Navigation("ClaimLine");
                });

            modelBuilder.Entity("Telebill.Models.Diagnosis", b =>
                {
                    b.HasOne("Telebill.Models.Encounter", "Encounter")
                        .WithMany("Diagnoses")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Diagnosis__Encou__10566F31");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("Telebill.Models.EligibilityRef", b =>
                {
                    b.HasOne("Telebill.Models.Coverage", "Coverage")
                        .WithMany("EligibilityRefs")
                        .HasForeignKey("CoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Eligibili__Cover__7D439ABD");

                    b.Navigation("Coverage");
                });

            modelBuilder.Entity("Telebill.Models.Encounter", b =>
                {
                    b.HasOne("Telebill.Models.Patient", "Patient")
                        .WithMany("Encounters")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Encounter__Patie__01142BA1");

                    b.HasOne("Telebill.Models.Provider", "Provider")
                        .WithMany("Encounters")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Encounter__Provi__02084FDA");

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Telebill.Models.FeeSchedule", b =>
                {
                    b.HasOne("Telebill.Models.PayerPlan", "Plan")
                        .WithMany("FeeSchedules")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__FeeSchedu__PlanI__70DDC3D8");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Telebill.Models.Notification", b =>
                {
                    b.HasOne("Telebill.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Notificat__UserI__6442E2C9");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Telebill.Models.PatientBalance", b =>
                {
                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("PatientBalances")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK__PatientBa__Claim__4D5F7D71");

                    b.HasOne("Telebill.Models.Patient", "Patient")
                        .WithMany("PatientBalances")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PatientBa__Patie__4C6B5938");

                    b.Navigation("Claim");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Telebill.Models.PayerPlan", b =>
                {
                    b.HasOne("Telebill.Models.Payer", "Payer")
                        .WithMany("PayerPlans")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PayerPlan__Payer__6C190EBB");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("Telebill.Models.PaymentPost", b =>
                {
                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("PaymentPosts")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PaymentPo__Claim__46B27FE2");

                    b.HasOne("Telebill.Models.ClaimLine", "ClaimLine")
                        .WithMany("PaymentPosts")
                        .HasForeignKey("ClaimLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK__PaymentPo__Claim__47A6A41B");

                    b.HasOne("Telebill.Models.User", "PostedByNavigation")
                        .WithMany("PaymentPosts")
                        .HasForeignKey("PostedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__PaymentPo__Poste__498EEC8D");

                    b.Navigation("Claim");

                    b.Navigation("ClaimLine");

                    b.Navigation("PostedByNavigation");
                });

            modelBuilder.Entity("Telebill.Models.PriorAuth", b =>
                {
                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("PriorAuths")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PriorAuth__Claim__31B762FC");

                    b.HasOne("Telebill.Models.PayerPlan", "Plan")
                        .WithMany("PriorAuths")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__PriorAuth__PlanI__32AB8735");

                    b.Navigation("Claim");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Telebill.Models.RemitRef", b =>
                {
                    b.HasOne("Telebill.Models.SubmissionBatch", "Batch")
                        .WithMany("RemitRefs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__RemitRef__BatchI__42E1EEFE");

                    b.HasOne("Telebill.Models.Payer", "Payer")
                        .WithMany("RemitRefs")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__RemitRef__PayerI__41EDCAC5");

                    b.Navigation("Batch");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("Telebill.Models.ScrubIssue", b =>
                {
                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("ScrubIssues")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ScrubIssu__Claim__2739D489");

                    b.HasOne("Telebill.Models.ClaimLine", "ClaimLine")
                        .WithMany("ScrubIssues")
                        .HasForeignKey("ClaimLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK__ScrubIssu__Claim__282DF8C2");

                    b.HasOne("Telebill.Models.ScrubRule", "Rule")
                        .WithMany("ScrubIssues")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ScrubIssu__RuleI__29221CFB");

                    b.Navigation("Claim");

                    b.Navigation("ClaimLine");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Telebill.Models.Statement", b =>
                {
                    b.HasOne("Telebill.Models.Patient", "Patient")
                        .WithMany("Statements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Statement__Patie__503BEA1C");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Telebill.Models.SubmissionRef", b =>
                {
                    b.HasOne("Telebill.Models.SubmissionBatch", "Batch")
                        .WithMany("SubmissionRefs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Submissio__Batch__3D2915A8");

                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("SubmissionRefs")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Submissio__Claim__3E1D39E1");

                    b.Navigation("Batch");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Telebill.Models.X12837pRef", b =>
                {
                    b.HasOne("Telebill.Models.Claim", "Claim")
                        .WithMany("X12837pRefs")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__X12_837P___Claim__2DE6D218");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Telebill.Models.Claim", b =>
                {
                    b.Navigation("Arworkitems");

                    b.Navigation("AttachmentRefs");

                    b.Navigation("ClaimLines");

                    b.Navigation("Denials");

                    b.Navigation("PatientBalances");

                    b.Navigation("PaymentPosts");

                    b.Navigation("PriorAuths");

                    b.Navigation("ScrubIssues");

                    b.Navigation("SubmissionRefs");

                    b.Navigation("X12837pRefs");
                });

            modelBuilder.Entity("Telebill.Models.ClaimLine", b =>
                {
                    b.Navigation("Denials");

                    b.Navigation("PaymentPosts");

                    b.Navigation("ScrubIssues");
                });

            modelBuilder.Entity("Telebill.Models.Coverage", b =>
                {
                    b.Navigation("EligibilityRefs");
                });

            modelBuilder.Entity("Telebill.Models.Denial", b =>
                {
                    b.Navigation("Appeals");
                });

            modelBuilder.Entity("Telebill.Models.Encounter", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("ChargeLines");

                    b.Navigation("Claims");

                    b.Navigation("CodingLocks");

                    b.Navigation("Diagnoses");
                });

            modelBuilder.Entity("Telebill.Models.Patient", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Coverages");

                    b.Navigation("Encounters");

                    b.Navigation("PatientBalances");

                    b.Navigation("Statements");
                });

            modelBuilder.Entity("Telebill.Models.Payer", b =>
                {
                    b.Navigation("PayerPlans");

                    b.Navigation("RemitRefs");
                });

            modelBuilder.Entity("Telebill.Models.PayerPlan", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Coverages");

                    b.Navigation("FeeSchedules");

                    b.Navigation("PriorAuths");
                });

            modelBuilder.Entity("Telebill.Models.Provider", b =>
                {
                    b.Navigation("Attestations");

                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("Telebill.Models.ScrubRule", b =>
                {
                    b.Navigation("ScrubIssues");
                });

            modelBuilder.Entity("Telebill.Models.SubmissionBatch", b =>
                {
                    b.Navigation("RemitRefs");

                    b.Navigation("SubmissionRefs");
                });

            modelBuilder.Entity("Telebill.Models.User", b =>
                {
                    b.Navigation("Arworkitems");

                    b.Navigation("AttachmentRefs");

                    b.Navigation("AuditLogs");

                    b.Navigation("CodingLocks");

                    b.Navigation("Notifications");

                    b.Navigation("PaymentPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
